### ISSUE TITLE
UID/GID of user inside container

### ISSUE THREAD

**Issue by isegals** [cenk1cenk2/docker-seafile-cli#1]
Hello. Is it possible to add UID and GID to environment variable, so we can use it to set permissions on synced files?

**Comment by cenk1cenk2** [comment]
Hello @isegals,

You can directly use the docker's `user` parameter since this container has no default user set for it.

Something like below should work for the given case if I am not missing something.

```yaml
version: "3"
services:
  seafile-cli:
    image: cenk1cenk2/seafile-cli:latest
    user: '1000:1000'
    env_file: .env
    volumes:
      - ./volumes/test/:/data/df535a2b-f663-4ee2-a690-1feb8bb792a3/
      - ./volumes/seafile:/seafile
```
